name: Build and Test

on:
  push:
    branches:
    - main
    - master
    - release/**
  pull_request:
    branches:
    - main
    - master
    - release/**
  workflow_dispatch:

env:
  NODE_VERSION: ${{ vars.NODE_VERSION && vars.NODE_VERSION || '20' }}
  REGISTRY: https://npm.pkg.github.com
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v4

    - name: "Install dependencies and run tests"
      uses: StudioWhyNot/act/common/npm/npm-test@master
      with:
        nodeVersion: ${{ env.NODE_VERSION }}
        testCommand: npm run test:coverage
        uploadCoverage: true
        apiKeys: ${{ env.NODE_AUTH_TOKEN }}
