name: Build

on:
  push:
    branches:
    - main
    - master
    - release/**
  pull_request:
    branches:
    - main
    - master
    - release/**
  workflow_dispatch:

env:
  NODE_VERSION: ${{ vars.NODE_VERSION && vars.NODE_VERSION || '20' }}
  REGISTRY: https://npm.pkg.github.com
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Install dependencies and run tests"
      uses: StudioWhyNot/act/common/npm/npm-test@master
      with:
        nodeVersion: ${{ env.NODE_VERSION }}
        testCommand: npm run test:coverage
        uploadCoverage: true
        authUrls: ${{ env.REGISTRY }}
        apiKeys: ${{ env.NODE_AUTH_TOKEN }}

    - name: "Get version from package.json"
      id: version
      uses: StudioWhyNot/act/common/yq/yq-expression@master
      with:
        expression: .version
        input: package.json

    - name: "Pack package"
      if: ${{ github.event_name == 'push' }}
      id: pack
      uses: StudioWhyNot/act/common/npm/npm-pack@master
      with:
        version: ${{ steps.version.outputs.result }}
        nodeVersion: ${{ env.NODE_VERSION }}
        buildScript: build
        outputDirectory: out

    - name: "Upload Artifacts"
      if: ${{ github.event_name == 'push' }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ steps.pack.outputs.tgzName }}
        path: ${{ steps.pack.outputs.tgz }}

    # - name: "Publish the NPM package"
    #   if: ${{ github.event_name == 'push' }}
    #   uses: StudioWhyNot/act/common/npm/npm-push@master
    #   with:
    #     tgz: ${{ steps.pack.outputs.tgz }}
    #     registry: ${{ env.REGISTRY }}
    #     apiKey: ${{ env.NODE_AUTH_TOKEN }}
    #     access: public
